// AUTO-GENERATED by scripts/sync-gallery.mjs — do not edit by hand.
// Source: Google Drive folder, synced at build time. Regenerate with
// `npm run sync:gallery` (requires Drive credentials) or on each deploy.

export type GalleryPhoto = { src: string; set: string; alt: string };

export const galleryPhotos: GalleryPhoto[] = [
  {
    "src": "/images/gallery/drive/05c953dc-6d71-4359-bcb8-2b656999b24b-1_W5cG03.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-0935-1xEfDhMd.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-7150-1_5fT4hN.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-0543-1B0F3eC-.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-0542-11FHYnmO.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1368-original-1mWK7pqG.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1320-original-1dKJfiNQ.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1363-original-169DmYXk.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1397-original-1N5dPi-l.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1356-original-1ZrJr_0W.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1357-original-1W94B96j.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1380-original-10Rr1D42.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1414-original-1AQioeI8.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1373-original-1uR4Pj_i.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1483-original-1XHKVdkM.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1407-original-1N1T1xyL.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1374-original-1FhhT6uV.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1408-original-1tgaXL7d.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1429-original-1auekB6q.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1394-original-1ryxJO34.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-1470-original-1hRKGRcm.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-0551-1MU4PHm-.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-0543-1zpIuRbV.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/dsc00419-1sIjd6TX.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/st-relaunchparty-550-1zKuSr5H.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/a84f81c9-0567-447b-bae5-0b2cb1859193-1eAEsw2E.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/108d9b82-31c9-409a-b2c9-648e20ee47ea-1PP6xhkc.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/d034c7b7-bf38-4efa-89ee-2627b68c5511-17CylarL.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/fd0dfa9c-1abb-4082-9525-5d4ea934cb5d-196XIW5f.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/dsc00453-1XBQNhpG.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/dsc00487-10R-loKK.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/163f41ce-5aaf-48e5-b4a4-582c99974503-17DJOyVF.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/dsc01274-1RYIWoAq.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/dsc01286-114BzaFq.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/dsc01272-1U5ikfdm.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/iqm-4932-1sZc6Bb8.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6861-1LRHX8VR.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/dscn1144-1Eg5vzIN.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-4851-1XgShbd4.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/3dde668f-94d8-4a0e-a8fa-a36821f3f4fa-1j4qL2Wc.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/aa5274f7-2380-4ac9-9859-0fabd15dd211-1AjHmsR4.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/robimg-exclusivektown-10262024-687-12H95ffn.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6853-1mqk4T4v.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6848-1_Lu5KRV.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6849-1Z_usEcL.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6854-11e4UFpB.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/robimg-exclusivektown-10262024-586-1xQ-uqN_.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/robimg-exclusivektown-10262024-558-1orDrsv4.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6850-1R-FQbtz.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6852-1RlWwviZ.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6851-1VJM8uXW.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6860-1udewl1d.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6846-19bWzDc4.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6859-1jI2UaR0.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6855-18KApMjE.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6847-1yV1FwXP.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9828-15fJA-dY.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6833-1975cWD5.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-5428-1suUeyYK.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6857-1K_BqYWV.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6858-1QPdi93g.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-6856-1X3ZVBrc.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9935-1vJWi3_E.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9937-1-d8xccU.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9931-1nW7oN0y.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9934-1Vp2C-qR.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9929-15-COmEd.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/01jdy0z1amzcg4acc6n96zhez8-low-res-branded-1nRd4kQx.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9927-1NVy0EZk.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/01jdy0p0jqage66jdg39883g75-low-res-branded-1tYzJN_Z.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-4850-1jQ-NBIT.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9936-1B9n_MXG.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9943-1xziL_0r.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9093-1A6LzZDZ.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9945-1xssX29-.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9939-1wQCazyT.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9942-11lohJmv.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9938-1hDmaqF2.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9940-1vRwOfnA.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9944-1KRyZfx_.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-9941-15HY6F8s.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-3480-1FwmY891.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/01jx4q68cq2csxvy92j11tg9bz-low-res-branded-10vEBFpP.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/106-0003-10bb_yGQ.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/105-9996-1upFt-YN.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/01jx4q15wqsgpp4whpzpeqkp1x-low-res-branded-127EnqIo.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-3483-17-sQT1M.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-3496-1UzmWpUO.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-3495-16BC0Ub1.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-3482-1wJGmXAt.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-2916-1WLP7sih.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/b1368eb2-6f61-4f1d-8762-bd72ece7df51-1TED8eTg.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-4023-1kwE8uhg.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-2282-1m-yRz0E.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-4020-1ljhfLEH.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-4019-19y5CO7y.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-4021-1TPzdUBU.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/img-2912-183c4X1i.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/8e9bad19-75c0-4f4c-8124-ac604fd30849-1zeS_GgD.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/collage-11-1FX3ZqGJ.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/capture-one-catalog3261-11l12GjZ.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/capture-one-catalog3180-14x9cTIs.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/capture-one-catalog3215-1eyOwJ5l.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/capture-one-catalog3104-1V7M2F24.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/capture-one-catalog3075-1H4CsGc8.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/capture-one-catalog3062-1EpXfq7t.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/capture-one-catalog3024-1MERW5A6.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/capture-one-catalog2982-1M6qjMhJ.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/capture-one-catalog2925-1R4o-khd.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/capture-one-catalog2906-1-1loG7qIf.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/capture-one-catalog2863-1QwQTb7s.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/capture-one-catalog2833-1MA1zsy4.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/skim-albumart-2-1nQfIp94.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/skim-baby-1fUBoidz.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/skim-3-1E0L-g3c.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/skim-2-1w0ZeSAe.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/glv8216-1PNX1me-.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/glv8196-1g9oLv8I.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/glv7977-1VisFiND.webp",
    "set": "sets",
    "alt": "skim live set"
  },
  {
    "src": "/images/gallery/drive/glv7915-1-1QOuEhdC.webp",
    "set": "sets",
    "alt": "skim live set"
  }
];
